repos:
- repo: local
  hooks:
  - id: convert-to-webp
    name: Convert images to WebP
    description: This hook converts image files to WebP format.
    entry: webp-hook
    language: python
    files: \.(png|jpg|jpeg|gif|bmp|tiff)$
    additional_dependencies:
      - Pillow
