name: Run tests on pull requests

on: [pull_request]

jobs:
  run-tests:
    runs-on: ubuntu-latest
    name: Run test suite

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup uv
        uses: astral-sh/setup-uv@v7

      - name: Install dependencies
        run: uv sync --dev

      - name: Run tests
        run: uv run pytest

      # https://github.com/codecov/codecov-action
      - name: Upload code coverage
        uses: codecov/codecov-action@v2
        with:
          # fail_ci_if_error: true # optional (default = false)
          verbose: true # optional (default = false)
